version: "3.8"

services:

  ros2-base:
    build:
      context: "docker/ros2"
      target: ros2-base
    init: true
    volumes:
      - "./docker/ros2/src:/ros2_ws/src"

  ros2-desktop:
    build:
      context: "docker/ros2"
      target: ros2-desktop
    init: true
    volumes:
      - "./docker/ros2/src:/ros2_ws/src"

  ros2-teensy-firmware-builder:
    build:
      context: "docker/ros2"
      target: ros2-base-and-micro-ros-and-platformio
    init: true
    privileged: true
    volumes:
      - "./teensy:/micro_ros_ws/pio_project"
      - "./docker/ros2/caches/.pio-system:/micro_ros_ws/.platformio"
    command: /bin/bash -c "cd /micro_ros_ws/pio_project && pio run"

  ros2-teensy-firmware-flasher:
    build:
      context: "docker/ros2"
      target: ros2-base-and-micro-ros-and-platformio
    init: true
    privileged: true
    volumes:
      - "./teensy:/micro_ros_ws/pio_project"
      - "./docker/ros2/caches/.pio-system:/micro_ros_ws/.platformio"
      - "/dev:/dev"
    command: /bin/bash -c "cd /micro_ros_ws/pio_project && pio run --target upload"

